# Generated by Django 2.1 on 2019-08-03 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CascadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SetNullModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TertiaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ConcreteModel',
            fields=[
                ('mainmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='test_app.MainModel')),
                ('other_name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('test_app.mainmodel',),
        ),
        migrations.AddField(
            model_name='throughmodel',
            name='main_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.MainModel'),
        ),
        migrations.AddField(
            model_name='throughmodel',
            name='tertiary_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.TertiaryModel'),
        ),
        migrations.AddField(
            model_name='tertiarymodel',
            name='main_models',
            field=models.ManyToManyField(through='test_app.ThroughModel', to='test_app.MainModel'),
        ),
        migrations.AddField(
            model_name='setnullmodel',
            name='main_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.MainModel'),
        ),
        migrations.AddField(
            model_name='secondarymodel',
            name='main_models',
            field=models.ManyToManyField(to='test_app.MainModel'),
        ),
        migrations.AddField(
            model_name='protectmodel',
            name='main_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.MainModel'),
        ),
        migrations.AddField(
            model_name='cascademodel',
            name='main_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.MainModel'),
        ),
        migrations.CreateModel(
            name='ProxyModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('test_app.mainmodel',),
        ),
    ]
